### ISSUE TITLE
Navigation cannot be edited

### ISSUE THREAD

**Issue by t00x** [havok89/Hoosk#10]
This is a great CMS! I mean seriously.

I need some advices on how to add/delete or edit the Navigation menu. The Navigation module seems not working as expected. I tried to add a new menu after creating a page but nothing happen (but it is working in the demo site http://demo.hoosk.org/). 

Adding a new Navigation also not working (also not working in demo site as well).

Also, the default menu - News and Contact won't disappear after deleting the demo page - News and Contact. A new menu name will appear in the drop down option after creating a new page and can be added to the menu list but it will disappear again after clicking the save button.

Would appreciate if you could help on this. Thank you.

**Comment by havok89** [comment]
Sorry for delay on this, the issue was down to moving to fontawesome for dashboard icons, the default install SQL contained the old "icon-remove" class instead of "fa fa-remove"

Have pushed an updated install.sql

You can fix your own install by editing the navEdit field in the database for the header nav as above

**Comment by t00x** [comment]
Thank you for your reply. Hoosk CMS has improved quite a number of features! Well done.
