### ISSUE TITLE
Base_url() Navigation does not work

### ISSUE THREAD

**Issue by Afdhal-Mahdi** [havok89/Hoosk#31]
Base_url() Navigation does not work.
On the front page the header menu does not point to base_url()

**Comment by havok89** [comment]
the system uses the constant BASE_URL which you set up during install and is in your config.php file

**Comment by Afdhal-Mahdi** [comment]
In the config is appropriate, because base_url elsewhere is not a problem

**Comment by kingdominc** [comment]
@Afdhal-Mahdi  - If your a CodeIgniter expert you already know that in the url helper there is a function called base_url. However Hoosk uses a CONSTANT of BASE_URL instead of utilizing the helper function.

To hopefully clear this up for others who may be reading these issues:
base_url() is a function in the url helper. This function is not utilized by Hoosk.
BASE_URL is a constant defined in your config.php (the one in your base folder, not the one in the config folder)
