### ISSUE TITLE
Can't login to admin page

### ISSUE THREAD

**Issue by milstrike** [havok89/Hoosk#34]
I have successfully installed hoosk on my server. No problems happened, I can login to the admin page.

However, after I moved it to another server (with the same specs), I can not login to the admin page.
There are no error messages, but can not log in to the admin page.
If you use the wrong username / password, then an error message appears.

I've tried various things, including deleting the value in $ config ["cookie_domain"], truncate the session table, but still nothing changes.

is it any idea for this..?

**Comment by havok89** [comment]
When it doesnt give an error message at the log in page and you know the details are correct it is because it isnt creating the correct cookie to allow you to log in, no error message is being shown because the database values are correct.

When you have moved server is the URL still the same or has it changed? it sounds like an issue with the config file.

**Comment by milstrike** [comment]
the URL changed.., 

when moving to another server, I change the URL. then I reconfigure the config.php file in the root directory. 

I read some issues here, and there are some tricks, but after I try, it still does not work.

Server information:
PHP 5.6
Apache 2.4

**Comment by milstrike** [comment]
Thanks for the help.., I can login to admin page now...
